// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BxMessageAltX: typeof import('~icons/bx/message-alt-x')['default']
    CarbonTemplate: typeof import('~icons/carbon/template')['default']
    Footer: typeof import('./components/Footer/index.vue')['default']
    IconoirPeopleRounded: typeof import('~icons/iconoir/people-rounded')['default']
    Logo: typeof import('./components/Logo/index.vue')['default']
    LogosVue: typeof import('~icons/logos/vue')['default']
    MdiTranslate: typeof import('~icons/mdi/translate')['default']
    RouterView: typeof import('vue-router')['RouterView']
    VaadinHomeO: typeof import('~icons/vaadin/home-o')['default']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
  }
}

export { }
